### ISSUE TITLE
Bad Battery Status

### ISSUE THREAD

**Issue by agintz** [PiSupply/PiJuice#353] opened 2019-08-09 09:40 UTC
Hi,
I just noticed a little bug on battery status. With pijuice_cli & I2C communication, I get:

- NORMAL: when the battery is plugged and the "GPIO power input" status is PRESENT whereas it should be CHARGING_FROM_5V_IO,
- CHARGING_FROM_IN: when the battery is UNplugged and the "USB micro power input" status is PRESENT whereas it should be NOT_PRESENT.

Here are the software version I used:

- firmware version = 1.3.
- pijuice-base package = 1.5

Thank you, yet, for your really good job!

**Comment by tvoverbeek** [comment] 2019-08-18 16:37
First one is not a bug. Status 'NORMAL' instead of 'CHARGING_FROM_5V_IO' means the battery is delivering power and the GPIO cannot deliver sufficient power for charging.
The second one could be a bug, but detecting battery not connected is not reliable.
Closing the issue

**Closed by tvoverbeek** 2019-08-18 16:37 UTC
