### ISSUE TITLE
Firmware GUI Progress Update Hangs

### ISSUE THREAD

**Issue by ChristopherRush** [PiSupply/PiJuice#253] opened 2018-12-20 11:29 UTC
@shawaj @tvoverbeek Updated from v1.1 to latest version v1.2. 

<img width="567" alt="screen shot 2018-12-20 at 11 02 02" src="https://user-images.githubusercontent.com/1878314/50282346-5fa12c80-044a-11e9-86e3-63e9c9db226b.png">

**Comment by ChristopherRush** [comment] 2018-12-20 13:18
After waiting a while I closed the window and then opened the Firmware page again. It had indicated that the Firmware did indeed flash.

**Comment by shawaj** [comment] 2018-12-20 14:30
@ChristopherRush so you think there is some bug in it?

**Comment by ChristopherRush** [comment] 2018-12-20 14:33
@shawaj Yes, the screenshot above just doesn't update from that state.

**Comment by shawaj** [comment] 2018-12-20 14:37
Ahh ok, sorry, I thought you meant you came back to it and it had worked. But you mean you closed it and looked again and it showed the new version?

**Comment by ChristopherRush** [comment] 2018-12-20 14:42
When I came back to the Firmware page it had updated it. The issue is with the status screen (as per the screenshot) not updating.

**Comment by tvoverbeek** [comment] 2018-12-20 14:44
Will investigate with update from 1.1 to 1.2.
@ChristopherRush Did you use the gui started from the menu or the tray icon after installing the 1.4 packages? The 1.4 packages do not show up yet in archive.raspberrypi.org, the latest one there are the 1.3.3 packages.
When installing the 1.4 packages manually, you will have to install pijuice-base first, followed by pijuice-gui. Might have to purge the existing packages first. When updating from the archive afternthey show up (apt-get update) all this is automatic.

**Comment by ChristopherRush** [comment] 2018-12-20 14:47
Yes, installed pijuice-base first then pijuice-gui both v1.4. Launched using the tray icon then headed over to Firmware to update to 1.2.

**Comment by tvoverbeek** [comment] 2018-12-20 19:11
Found the problem. Caused by the difference between a stream of bytes and a string in Python 3.
I obviously have not tested the firmware update against Python 3.
@shawaj Can you inform Phil Ewell to hold off on making the 1.4 debs available, so I can regenerate them with the fix, or shall we go immediately to 1.4.1?

**Comment by shawaj** [comment] 2018-12-20 19:12
Will email @pelwell and Serge to see if they can help!

**Closed** 2019-09-15 21:35 UTC
