### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by victorromeo** [PiSupply/PiJuice#454] opened 2020-01-31 10:20 UTC
I've got  a wish list for new features to add to the PiJuice api please.

- Setting up the PiJuice via a JSON blob, to restore from source control
- Scripts on IO1 and IO2 pins rising and falling edges
- Option for a 5V peripheral supply while Pi is Off
- Built in algorithm to determine an approximate time remaining
- Built in lifecycle assistant to measure when batteries are needing replacing
- Pub/Sub events on the IO1 and IO2 pins, similar to gpiozero callback events
- Inline USB protection to prevent killing a Pi (A piece which adapts onto the USB port)
- GPIO pin protection
- A way to switch off the camera via the PiJuice, (Camera plugs into PiJuice, PiJuice regulates and switches the camera on and off)
- Software re settable fuses
- Headless options for the Pi4, to slim the unit down

Food for thought

**Comment by ChristopherRush** [comment] 2020-01-31 10:30
With regards to the last option we have - https://uk.pi-supply.com/products/pijuice-zero

**Comment by shawaj** [comment] 2020-10-24 03:17
Closing this as it's a duplicate of #451

**Closed by shawaj** 2020-10-24 03:17 UTC
