### ISSUE TITLE
PiJuice and PiPoE

### ISSUE THREAD

**Issue by klint-k** [PiSupply/PiJuice#267] opened 2019-01-10 00:44 UTC
PiJuice and PiPoE

I would like to know how to install and setup the combination of PiJuice and PiPoE?

**Comment by shawaj** [comment] 2019-01-10 07:06
This is a duplicate of https://github.com/PiSupply/PiPoE/issues/7

Will close this and continue over there

**Closed by shawaj** 2019-01-10 07:06 UTC
